name: weather-ai
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blosc=1.21.5=hc2324a3_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - cartopy=0.25.0=py310h0158d43_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - cftime=1.6.5=py310hf779ad0_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda=12.4.1=0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=12.4.1=0
  - cuda-compiler=12.6.2=0
  - cuda-crt-tools=12.4.131=ha770c72_1
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-static=12.4.127=0
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-cupti-static=12.4.127=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-demo-suite=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-libraries-dev=12.6.0=0
  - cuda-libraries-static=12.4.1=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvcc-tools=12.4.131=hd3aeb46_1
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvrtc-static=12.4.127=0
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-nvvm-tools=12.4.131=h59595ed_1
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=12.4.1=0
  - cuda-tools=12.4.1=0
  - cuda-version=12.4=h3060b56_3
  - cuda-visual-tools=12.6.0=0
  - cudnn=8.9.7.29=h092f7fd_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.19=py310h8a20257_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dominate=2.9.1=pyhd8ed1ab_1
  - double-conversion=3.4.0=hecca717_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.20.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h267a509_2
  - gast=0.7.0=pyhd8ed1ab_0
  - gds-tools=1.9.1.3=0
  - geos=3.14.1=h480dda7_0
  - giflib=5.2.2=hd590300_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=20_linux64_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=20_linux64_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.7=default_h087397f_0
  - libcublas=12.4.5.8=he02047a_2
  - libcublas-dev=12.4.5.8=0
  - libcublas-static=12.4.5.8=0
  - libcudnn=9.12.0.46=h24322f0_0
  - libcudnn-dev=9.12.0.46=h2b6041c_0
  - libcufft=11.2.1.3=he02047a_2
  - libcufft-dev=11.2.1.3=0
  - libcufft-static=11.2.1.3=0
  - libcufile=1.9.1.3=he02047a_2
  - libcufile-dev=1.9.1.3=0
  - libcufile-static=1.9.1.3=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.5.147=he02047a_2
  - libcurand-dev=10.3.5.147=0
  - libcurand-static=10.3.5.147=0
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.6.1.9=he02047a_2
  - libcusolver-dev=11.6.1.9=0
  - libcusolver-static=11.6.1.9=0
  - libcusparse=12.3.1.170=he02047a_2
  - libcusparse-dev=12.3.1.170=0
  - libcusparse-static=12.3.1.170=0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.80.2=hf974151_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=20_linux64_mkl
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.2.5.30=he02047a_2
  - libnpp-dev=12.2.5.30=0
  - libnpp-static=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.4.127=he02047a_2
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=he02047a_2
  - libnvjpeg-dev=12.3.1.117=0
  - libnvjpeg-static=12.3.1.117=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.6=h0fd0de7_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.11=hc183893_2
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libvulkan-loader=1.3.290.0=h4f7c5cb_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=hc051c1a_1
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.9.1=py310hff52083_1
  - matplotlib-base=3.9.1=py310hf02ac8c_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metpy=1.7.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2023.2.0=ha770c72_50498
  - ml_dtypes=0.3.2=py310hcc13569_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - namex=0.1.0=pyhd8ed1ab_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.6.5=nompi_py310h3aa39b3_102
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nsight-compute=2024.1.1.4=0
  - nspr=4.38=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.18.0=py310h03d9f68_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.3.0=py310hf73ecf8_0
  - pint=0.24.4=pyhe01879c_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.4.1=hb784bbd_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.6.1=py310h3160ae9_9
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=hc9dc06e_21
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.30.0=py310hd8f68c5_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - send2trash=2.0.0=pyha191276_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py310hc8bbb35_2
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=hceb3a55_1
  - tensorflow-base=2.16.1=cuda120py310h68a2f4f_0
  - tensorflow-estimator=2.16.1=cuda120py310h1fd330c_0
  - tensorflow-gpu=2.16.1=cuda120py310hb76ca00_0
  - termcolor=3.3.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.5.1=py310_cu124
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu124
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.1=py310h7c4b9e2_1
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-cursor=0.1.4=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.2.13=h4ab18f5_6
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.12.0
      - array-record==0.8.1
      - backcall==0.2.0
      - diffusers==0.36.0
      - dm-tree==0.1.9
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - einops==0.8.1
      - etils==1.13.0
      - flatbuffers==25.12.19
      - fsspec==2025.12.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - imageio==2.37.2
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - ipython==8.12.3
      - keras==3.12.0
      - keras-tuner==1.4.8
      - kt-legacy==1.0.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - ml-dtypes==0.5.4
      - opencv-python==4.12.0.88
      - promise==2.3
      - protobuf==4.21.12
      - pyarrow==22.0.0
      - regex==2025.11.3
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - simple-parsing==0.1.7
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.9
      - tensorflow-hub==0.16.1
      - tensorflow-metadata==1.17.2
      - tf-keras==2.20.1
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - tqdm==4.67.1
      - transformers==4.57.3
      - typeguard==2.13.3
      - yarg==0.1.9
prefix: /home/repiece/miniconda3/envs/weather-ai
